### ISSUE TITLE
Accent Positioning: inverted breve and caron

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Vollkorn-Typeface#12]
Testing these VF files in typetools.typenetwork.com
VollkornSC[wght].ttf
Vollkorn[wght].ttf
Vollkorn-Italic[wght].ttf

All inverted breves. One instance of cap I.sc caron.

<img width="249" alt="Vollkorn SC inverted breves" src="https://user-images.githubusercontent.com/6576107/87261603-d9619680-c484-11ea-9b14-c68094a34bb8.png">

<img width="221" alt="Vollkorn Italic inverted breve" src="https://user-images.githubusercontent.com/6576107/87261592-d070c500-c484-11ea-8097-0320db7e3ec1.png">

<img width="228" alt="Vollkorn SC caron" src="https://user-images.githubusercontent.com/6576107/87261597-d4044c00-c484-11ea-9a01-2dd888d676cb.png">

**Comment by djrrb** [comment]
Wish there were a better solution, but I have addressed this by decomposing all rotated or scaled components in the sources (there were a bunch of them). 

<img width="219" alt="Screen Shot 2020-07-17 at 2 12 27 PM" src="https://user-images.githubusercontent.com/6578861/87818507-aaf30b00-c838-11ea-9100-a03a7fd9b47d.png">

**Comment by pichotta** [comment]
@pichotta   
Re-check decompositions.

**Comment by pichotta** [comment]
Done
