### ISSUE TITLE
Glyph naming

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Vollkorn-Typeface#5]
A few glyphs names different between SC styles.

Compared to 'VollkornSC-Regular'
VollkornSC-Black and
VollkornSC-ExtraBold has:

*Missing glyphs: _part.cent, _part.colonsign.sc, _part.dollar.sc, _part.naira.sc, _part.peso.sc

*Additional glyphs: _part.cedi.sc.black, _part.cent.black, _part.colonsign.sc.black, _part.dollar.sc.black, _part.naira.sc.black, _part.peso.sc.black

--------------

Compared to 'VollkornSC-Italic'

VollkornSC-ExtraBoldItalic
Compare VollkornSC-BlackItalic_
VollkornSC-Italic has:

*Missing glyphs_: _part.cent, _part.colonsign, _part.dollar, _part.guarani, _part.naira, _part.peso, _part.won
*Additional glyph_s: _part.cent.black, _part.colonsign.black, _part.dollar.black, _part.guarani.black, _part.naira.black, _part.peso.black, _part.won.black

and 

VollkornSC-BoldItalic
* Missing glyphs: _part.colonsign, _part.guarani, _part.peso, _part.won
* Additional glyphs: _part.colonsign.black, _part.guarani.black, _part.peso.black, _part.won.black

**Comment by moyogo** [comment]
This is on purpose, these components are used in the rvrn variant glyphs.
