### ISSUE TITLE
double acute/grave accents

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Vollkorn-Typeface#6]
Are these ok?

before:

<img width="321" alt="Screenshot 2020-04-29 at 10 35 36" src="https://user-images.githubusercontent.com/7525512/80581535-2fd24380-8a05-11ea-93f2-dc5d4cd4f89d.png">

after:

<img width="289" alt="Screenshot 2020-04-29 at 10 35 57" src="https://user-images.githubusercontent.com/7525512/80581564-3b256f00-8a05-11ea-9b52-5f260ca94ee8.png">

**Comment by moyogo** [comment]
Both forms are correct. I think the update was done after Vietnamese design review since that is the preferred form in Vietnamese.

**Comment by m4rc1e** [comment]
Thank you. I'll keep it as is.
