### ISSUE TITLE
Spacing: collision of ff ligs

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Vollkorn-Typeface#7]
![Vollkorn ff lig spacing 2020-07-04 at 11 15 05 AM](https://user-images.githubusercontent.com/6576107/86515748-4de36800-bde9-11ea-8656-adcc224094bb.png)

**Comment by djrrb** [comment]
@moyogo Sorry to bother, but do you have an idea of what’s going on here? I tried removing the anchors with no luck. I thought it was going to be like the finalpe issue in Rubik, but maybe it’s not?
